### ISSUE TITLE
Why the broken history?

### ISSUE THREAD

**Issue by alexanderadam** [r3id/clickhouse#1]
This is based on @maiha's [`clickhouse.cr`](https://github.com/maiha/clickhouse.cr), right?
May I ask what's the reason for the broken history? :thinking: 

The same goes for `ip2country`, `lucky_can`, `device_detector`, etc.

I'm just curious about the reason.

**Comment by r3id** [comment]
Because I re-wrote it and sorted out the issues I was having with it. This doesn't show the errors I was previously getting with their versions.
